### PR TITLE
Move parse package internally and modify Makefile

### LINKED ISSUE #131: Move parse package internally
In preparation for #109, I'd like to make some breaking changes to the `parse` package. This shouldn't affect any real users because the only real consumer of this package is the `tparse` CLI itself.

Mainly adding this issue in the odd event someone searches for "breaking changes" and/or explanation.

### PR DESCRIPTION
**Pull request by mfridman**
Fix #131 

This PR does a few things:

- moves the ./parse package into ./internal/parse
- add tools module to track golangci-lint
- minor updates to Makefile

### CODE REVIEW

**Review by ccoVeille — APPROVED** [review]
LGTM 👍

One question, you mention

> add tools module to track golangci-lint

I didn't find this one. I saw changes in Makefile, but that's it.

Is it what you were talking about?

I thought I would see something about toolchain entry in go.mod or something like that

**Comment by egonelbre** [comment]
Any specific reason parse package was moved to internal? It's been quite helpful to write custom tools for analyzing/processing the test output.

**Comment by mfridman** [comment]
> Any specific reason parse package was moved to internal? It's been quite helpful to write custom tools for analyzing/processing the test output.

Trying to get this project to a `v1` state I wanted to refactor and make some breaking changes to that package. It was quite coupled to the tool itself so I want to clean that up a bit.

Happy to move it out of `./internal` though if you think there's some use for it.

**Comment by mfridman** [comment]
> LGTM 👍
> 
> One question, you mention
> 
> > add tools module to track golangci-lint
> 
> I didn't find this one. I saw changes in Makefile, but that's it.
> 
> Is it what you were talking about?
> 
> I thought I would see something about toolchain entry in go.mod or something like that

I was experimenting with it (https://github.com/mfridman/tparse/pull/132/commits/189a95756e32496045d88976ac1e368d52387ffd), but at the end decided the project was way too simple so I reverted those changes and forgot to update the description. Ultimately waiting for https://github.com/golang/go/issues/48429 to land to improve the story around tool deps.

**Comment by egonelbre** [comment]
> Happy to move it out of ./internal though if you think there's some use for it.

Yeah, it does come up occasionally for me.

I sometimes use some other "internal" to indicate that it's not finalized, like `github.com/mfridman/tparse/exp/parse` or `github.com/mfridman/tparse/private/parse`.

But, yeah, I can keep using the older version if you want to clean up the parse package.

**Comment by mfridman** [comment]
Thanks for surfacing it, happy to move it back to the top level. There _might_ be some fairly minor breaking changes, but my ultimate goal is to make it an off-the-shelf parsing library and nail down the returned results.

**Pull request merged**
